version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27018:27017
    restart: always